# Generated by Django 4.0.4 on 2023-09-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
