# Generated by Django 4.0.4 on 2023-09-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0002_delete_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='image/%Y', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
