# Generated by Django 4.0.4 on 2023-09-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0004_rating_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
