# Generated by Django 4.0.4 on 2023-09-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0008_alter_rating_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
