# Generated by Django 4.0.4 on 2023-09-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0011_comment_rating_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP-адрес пользователя')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinahodka.film', verbose_name='Фильм')),
            ],
        ),
    ]
