# Generated by Django 4.0.4 on 2023-09-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinahodka', '0012_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
